package review

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/derzierau/hesper/relay/pkg/wire"
)

// Simple deterministic rules (phase 1, no judgement): which files are
// generated, formatting-only or moved, how risky a file and a change are,
// and the order to read the files in.

var (
	generatedNames = map[string]bool{
		"package-lock.json": true, "yarn.lock": true, "pnpm-lock.yaml": true, "bun.lockb": true, "go.sum": true,
		"cargo.lock": true, "gemfile.lock": true, "poetry.lock": true, "pipfile.lock": true, "uv.lock": true,
		"composer.lock": true, "podfile.lock": true, "package.resolved": true, "flake.lock": true, "mix.lock": true,
	}
	generatedPath   = regexp.MustCompile(`(^|/)(vendor|node_modules|dist|build|\.build|generated|__generated__|__snapshots__)/|\.pb\.go$|_pb2\.py$|\.pb\.(swift|h|cc)$|[._]generated\.|\.gen\.|\.min\.(js|css)$|\.snap$|\.map$`)
	generatedMarker = regexp.MustCompile(`(?i)(code generated .* do not edit|@generated|auto-?generated|do not edit\b.*generated|generated by)`)

	// High risk: auth and secrets, migrations and schemas, deployment
	// and CI (rule, note).
	riskyPaths = []struct {
		re   *regexp.Regexp
		note string
	}{
		{regexp.MustCompile(`(?i)(^|[^a-z])(auth(n|z|entication|enticate|orization|orize|orizer)?|login|passwords?|passwd|secrets?|tokens?|credentials?|crypto|security|permissions?|oauth|keychain|jwt|certs?|certificates?|signing|entitlements|sudoers?)([^a-z]|$)|(^|/)\.env`), "touches auth or secrets"},
		{regexp.MustCompile(`(?i)(migration|migrate|schema|\.sql$|\.prisma$)`), "migration or schema"},
		{regexp.MustCompile(`(?i)(^|/)(\.github/workflows|\.gitlab-ci|\.circleci|deploy|terraform|helm|k8s)(/|\.|$)|(^|/)dockerfile|\.tf$`), "deployment or CI"},
	}
	// Depended on: build and dependency manifests, configuration,
	// interface and schema definitions.
	manifestNames = map[string]bool{
		"go.mod": true, "package.json": true, "package.swift": true, "cargo.toml": true, "pyproject.toml": true, "gemfile": true,
		"makefile": true, "justfile": true, "build.gradle": true, "pom.xml": true, "tsconfig.json": true, "setup.py": true,
	}
	configPath = regexp.MustCompile(`(?i)\.(ya?ml|toml|ini|conf|cfg|plist|xcconfig|proto|graphql|thrift|d\.ts)$|(^|/)(config|settings)\.|(^|/)requirements[^/]*\.txt$`)
	docPath    = regexp.MustCompile(`(?i)\.(md|markdown|rst|txt|adoc)$|(^|/)(docs?|documentation)/`)
	testDir    = regexp.MustCompile(`(?i)(^|/)(tests?|__tests__|spec|specs|testdata|fixtures)/`)
	testName   = regexp.MustCompile(`(?i)(_test\.go$|\.(test|spec)\.[a-z]+$|^test_[^/]+\.py$|_test\.py$|tests?\.swift$|test\.(java|kt|cs)$|_spec\.rb$)`)
)

// isGenerated: by name and path, or by a marker in the new file's first
// lines.
func isGenerated(f *wire.ReviewFile) bool {
	p := strings.ToLower(f.Path)
	if generatedNames[path.Base(p)] || generatedPath.MatchString(p) {
		return true
	}
	for _, h := range f.Hunks {
		for _, l := range h.Lines {
			if l.Kind != "-" && l.New > 0 && l.New <= 10 && generatedMarker.MatchString(l.Text) {
				return true
			}
		}
	}
	return false
}

func squeeze(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsSpace(r) {
			return -1
		}
		return r
	}, s)
}

// markFormatting flags the hunks whose changes are whitespace only, and
// the file when every hunk is (a modification or rename only).
func markFormatting(f *wire.ReviewFile) {
	all := len(f.Hunks) > 0
	for i := range f.Hunks {
		h := &f.Hunks[i]
		var removed, added strings.Builder
		changed := false
		for _, l := range h.Lines {
			switch l.Kind {
			case "-":
				removed.WriteString(squeeze(l.Text))
				changed = true
			case "+":
				added.WriteString(squeeze(l.Text))
				changed = true
			}
		}
		h.FormattingOnly = changed && removed.String() == added.String()
		all = all && h.FormattingOnly
	}
	f.FormattingOnly = all && (f.Status == wire.ReviewModified || f.Status == wire.ReviewRenamed)
}

// minMoved is the smallest block (non-blank lines) read as moved.
const minMoved = 3

// markMoved flags the hunks whose every changed line belongs to a block
// removed in one place and added unchanged (but for indentation) in
// another, in any file.
func markMoved(files []wire.ReviewFile) {
	type run struct {
		file, hunk, from, to int
		key                  string
	}
	var removed, added []run
	for fi := range files {
		for hi, h := range files[fi].Hunks {
			for i := 0; i < len(h.Lines); {
				kind := h.Lines[i].Kind
				if kind == " " {
					i++
					continue
				}
				start := i
				var b strings.Builder
				blank := 0
				for i < len(h.Lines) && h.Lines[i].Kind == kind {
					t := strings.TrimSpace(h.Lines[i].Text)
					if t == "" {
						blank++
					}
					b.WriteString(t)
					b.WriteByte('\n')
					i++
				}
				if i-start-blank < minMoved {
					continue
				}
				r := run{file: fi, hunk: hi, from: start, to: i, key: b.String()}
				if kind == "-" {
					removed = append(removed, r)
				} else {
					added = append(added, r)
				}
			}
		}
	}
	addedKeys := map[string][]run{}
	for _, r := range added {
		addedKeys[r.key] = append(addedKeys[r.key], r)
	}
	moved := map[[2]int][][2]int{} // hunk -> moved line ranges
	for _, r := range removed {
		for _, a := range addedKeys[r.key] {
			if a.file == r.file && a.hunk == r.hunk {
				continue // a block rewritten in place is no move
			}
			moved[[2]int{r.file, r.hunk}] = append(moved[[2]int{r.file, r.hunk}], [2]int{r.from, r.to})
			moved[[2]int{a.file, a.hunk}] = append(moved[[2]int{a.file, a.hunk}], [2]int{a.from, a.to})
		}
	}
	for key, ranges := range moved {
		h := &files[key[0]].Hunks[key[1]]
		in := make([]bool, len(h.Lines))
		for _, rg := range ranges {
			for i := rg[0]; i < rg[1]; i++ {
				in[i] = true
			}
		}
		all := true
		for i, l := range h.Lines {
			if l.Kind != " " && !in[i] {
				all = false
				break
			}
		}
		h.Moved = all
	}
}

// IsTest reports whether a path is a test (by its name or folder).
func IsTest(p string) bool {
	return testName.MatchString(path.Base(p)) || testDir.MatchString(p)
}

// testSubject is the stem a test file tests: "foo" for foo_test.go,
// foo.test.ts, test_foo.py, FooTests.swift.
func testSubject(p string) string {
	base := strings.ToLower(path.Base(p))
	base = strings.TrimSuffix(base, path.Ext(base))
	for _, cut := range []string{"_test", ".test", ".spec", "_spec", "tests", "test"} {
		if s, ok := strings.CutSuffix(base, cut); ok && s != "" {
			return strings.TrimRight(s, "_.-")
		}
	}
	if s, ok := strings.CutPrefix(base, "test_"); ok {
		return s
	}
	return base
}

func stem(p string) string {
	base := strings.ToLower(path.Base(p))
	return strings.TrimSuffix(base, path.Ext(base))
}

// Risk is one file's risk: its level and why.
type Risk struct {
	Level string
	Notes []string
}

var riskRank = map[string]int{wire.RiskLow: 0, wire.RiskMedium: 1, wire.RiskHigh: 2}

func higher(a, b string) string {
	if riskRank[b] > riskRank[a] {
		return b
	}
	return a
}

// FileRisk rates one changed file from its path, status and size:
// generated and formatting-only files are low; auth, secrets,
// migrations, schemas, deployment and CI high; deletions, dependency
// manifests and configuration, and large changes (over 300 lines)
// medium.
func FileRisk(p, status string, added, removed int, generated, formatting bool) Risk {
	r := Risk{Level: wire.RiskLow}
	if generated || formatting {
		return r
	}
	for _, rule := range riskyPaths {
		if rule.re.MatchString(p) {
			r.Level = wire.RiskHigh
			r.Notes = append(r.Notes, rule.note+": "+p)
			return r
		}
	}
	if status == wire.ReviewDeleted {
		r.Level = wire.RiskMedium
		r.Notes = append(r.Notes, "deletes "+p)
	}
	if manifestNames[strings.ToLower(path.Base(p))] {
		r.Level = wire.RiskMedium
		r.Notes = append(r.Notes, "dependencies or build: "+p)
	}
	if added+removed > 300 {
		r.Level = wire.RiskMedium
		r.Notes = append(r.Notes, fmt.Sprintf("large change: %s (%d lines)", p, added+removed))
	}
	return r
}

// ChangeRisk rates a whole change (review.list): the riskiest file, at
// least medium over 800 changed lines, and over 100 changed lines of code
// without a test changed. Notes are the files' notes and these.
func ChangeRisk(changes []Change) (string, []string) {
	level, notes := wire.RiskLow, []string{}
	total, code, tests := 0, 0, 0
	for _, c := range changes {
		generated := generatedNames[strings.ToLower(path.Base(c.Path))] || generatedPath.MatchString(strings.ToLower(c.Path))
		r := FileRisk(c.Path, c.Status, c.Added, c.Removed, generated, false)
		level = higher(level, r.Level)
		notes = append(notes, r.Notes...)
		if generated {
			continue
		}
		total += c.Added + c.Removed
		switch {
		case IsTest(c.Path):
			tests++
		case !docPath.MatchString(c.Path) && !c.Binary:
			code += c.Added + c.Removed
		}
	}
	if total > 800 {
		level = higher(level, wire.RiskMedium)
		notes = append(notes, fmt.Sprintf("large change: %d lines", total))
	}
	if code > 100 && tests == 0 {
		level = higher(level, wire.RiskMedium)
		notes = append(notes, fmt.Sprintf("no tests changed for %d lines of code", code))
	}
	return level, notes
}

// Reading order tiers: risky first, then what others depend on, code
// (each test right after its subject), tests without a changed subject,
// docs, formatting-only, generated.
const (
	tierRisky = iota
	tierDepended
	tierCode
	tierTests
	tierDocs
	tierFormatting
	tierGenerated
)

// readingOrder rates every file and returns the indexes of files in
// reading order: by tier, then risk, then size; the path only breaks
// ties. Never alphabetical.
func readingOrder(files []wire.ReviewFile) []int {
	tier := make([]int, len(files))
	for i := range files {
		f := &files[i]
		r := FileRisk(f.Path, f.Status, f.Added, f.Removed, f.Generated, f.FormattingOnly)
		f.Risk = r.Level
		base := strings.ToLower(path.Base(f.Path))
		switch {
		case f.Generated:
			tier[i] = tierGenerated
		case f.FormattingOnly:
			tier[i] = tierFormatting
		case r.Level == wire.RiskHigh:
			tier[i] = tierRisky
		case manifestNames[base] || configPath.MatchString(f.Path):
			tier[i] = tierDepended
		case IsTest(f.Path):
			tier[i] = tierTests
		case docPath.MatchString(f.Path):
			tier[i] = tierDocs
		default:
			tier[i] = tierCode
		}
	}
	less := func(i, j int) bool {
		if tier[i] != tier[j] {
			return tier[i] < tier[j]
		}
		if a, b := riskRank[files[i].Risk], riskRank[files[j].Risk]; a != b {
			return a > b
		}
		if a, b := files[i].Added+files[i].Removed, files[j].Added+files[j].Removed; a != b {
			return a > b
		}
		return files[i].Path < files[j].Path
	}
	var main, tests []int
	for i := range files {
		if tier[i] == tierTests {
			tests = append(tests, i)
		} else {
			main = append(main, i)
		}
	}
	sort.SliceStable(main, func(a, b int) bool { return less(main[a], main[b]) })
	sort.SliceStable(tests, func(a, b int) bool { return less(tests[a], tests[b]) })
	// Each test follows its subject: the same stem in its folder first,
	// else anywhere.
	after := map[int][]int{}
	var loose []int
	for _, t := range tests {
		subject := testSubject(files[t].Path)
		found := -1
		for _, m := range main {
			if tier[m] > tierCode || stem(files[m].Path) != subject {
				continue
			}
			if path.Dir(files[m].Path) == path.Dir(files[t].Path) {
				found = m
				break
			}
			if found < 0 {
				found = m
			}
		}
		if found < 0 {
			loose = append(loose, t)
			continue
		}
		after[found] = append(after[found], t)
	}
	order := make([]int, 0, len(files))
	placedLoose := false
	for _, m := range main {
		if !placedLoose && tier[m] > tierTests {
			order = append(order, loose...)
			placedLoose = true
		}
		order = append(order, m)
		order = append(order, after[m]...)
	}
	if !placedLoose {
		order = append(order, loose...)
	}
	return order
}
